import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { loadApiConfig } from './env.js';

/**
 * Storage for uploaded files: operator logos and metric workbooks.
 *
 * Uploads are the usual way an application like this gets compromised, so a few
 * rules are absolute here.
 *
 * **The path on disk owes nothing to the uploader.** It is built from the
 * organisation's id and a freshly generated file id, both UUIDs. The original
 * filename is recorded in the database for display and used when the file is
 * sent back, but it never touches the filesystem, which removes path traversal
 * as a category rather than as a case to defend against.
 *
 * **Type is decided by content, not by claim.** The browser's declared
 * content-type and the file extension are both attacker-controlled. What is
 * actually written is decided by inspecting the leading bytes.
 *
 * **Nothing is served statically.** Files live outside any web root and come
 * back only through authenticated, tenant-scoped endpoints, because a logo URL
 * that works without a session is a URL that works for anyone who finds it.
 */

export type ImageType = 'png' | 'jpg' | 'gif' | 'bmp';

export interface SniffedType {
  /** Canonical extension, from the bytes themselves. */
  kind: ImageType | 'xlsx';
  contentType: string;
}

/** Leading bytes that identify the formats this platform accepts. */
const SIGNATURES: ReadonlyArray<{ magic: readonly number[]; kind: SniffedType['kind']; contentType: string }> = [
  { magic: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], kind: 'png', contentType: 'image/png' },
  { magic: [0xff, 0xd8, 0xff], kind: 'jpg', contentType: 'image/jpeg' },
  { magic: [0x47, 0x49, 0x46, 0x38], kind: 'gif', contentType: 'image/gif' },
  { magic: [0x42, 0x4d], kind: 'bmp', contentType: 'image/bmp' },
  // xlsx and xlsm are both zip containers; which one is settled by the caller,
  // since the distinction is the macro part inside rather than the header.
  {
    magic: [0x50, 0x4b, 0x03, 0x04],
    kind: 'xlsx',
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  },
];

export function sniffType(bytes: Uint8Array): SniffedType | null {
  for (const signature of SIGNATURES) {
    if (signature.magic.every((byte, index) => bytes[index] === byte)) {
      return { kind: signature.kind, contentType: signature.contentType };
    }
  }
  return null;
}

export const IMAGE_TYPES: readonly ImageType[] = ['png', 'jpg', 'gif', 'bmp'];

export function isImageType(kind: SniffedType['kind']): kind is ImageType {
  return (IMAGE_TYPES as readonly string[]).includes(kind);
}

/** Upper bounds, generous enough for real files and far below anything abusive. */
export const MAX_LOGO_BYTES = 2 * 1024 * 1024;
export const MAX_WORKBOOK_BYTES = 30 * 1024 * 1024;

function storageRoot(): string {
  return resolve(loadApiConfig().storageDir);
}

/**
 * Where a file lives, given its owner and its id.
 *
 * Both components are UUIDs generated by this system, so the result cannot
 * escape the storage root however the upload was crafted. The check below is
 * belt and braces against a future caller passing something else.
 */
export function storagePathFor(organisationId: string, fileId: string): string {
  const root = storageRoot();
  const path = resolve(join(root, organisationId, fileId));

  if (!path.startsWith(root + '/')) {
    throw new Error('Refusing to store a file outside the storage root.');
  }
  return path;
}

export interface SavedFile {
  fileId: string;
  storagePath: string;
  sha256: string;
  byteSize: number;
  contentType: string;
  kind: SniffedType['kind'];
}

export async function saveFile(organisationId: string, bytes: Uint8Array, sniffed: SniffedType): Promise<SavedFile> {
  const fileId = randomUUID();
  const path = storagePathFor(organisationId, fileId);

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes, { mode: 0o600 });

  return {
    fileId,
    storagePath: path,
    sha256: createHash('sha256').update(bytes).digest('hex'),
    byteSize: bytes.byteLength,
    contentType: sniffed.contentType,
    kind: sniffed.kind,
  };
}

export async function readStoredBytes(storagePath: string): Promise<Uint8Array> {
  const root = storageRoot();
  const path = resolve(storagePath);

  // The path comes from the database rather than from a request, but reading
  // an arbitrary path because a row said so is exactly the shape of a bug worth
  // refusing outright.
  if (!path.startsWith(root + '/')) {
    throw new Error('Refusing to read a file from outside the storage root.');
  }
  return new Uint8Array(await readFile(path));
}

export async function deleteStoredBytes(storagePath: string): Promise<void> {
  const root = storageRoot();
  const path = resolve(storagePath);
  if (!path.startsWith(root + '/')) return;
  await rm(path, { force: true });
}

/**
 * A filename safe to put in a Content-Disposition header.
 *
 * Quotes and control characters would let a crafted filename break out of the
 * header and inject one of its own.
 */
export function safeDownloadName(filename: string, fallback: string): string {
  const cleaned = filename
    .replace(/[\u0000-\u001f\u007f"\\]/g, '')
    .replace(/[/\\]/g, '-')
    .trim();
  return cleaned === '' ? fallback : cleaned.slice(0, 180);
}
